### ISSUE TITLE
Daisy-chaining PatchSet fails to create branch

### ISSUE THREAD

**Issue by ndhaller** [tianocore/edk2-edkrepo#118]
Currently, two PatchSet can be chained together to create a dynamic branch.

If a third or more PatchSet is chained in a row, these PatchSet fail to create a dynamic branch when used, and non-gracefully fails when the PatchSet steps are attempted on the wrong branch or commit.

edkrepo 3.1.0

**Comment by ndhaller** [comment]
A proposed change.
https://github.com/tianocore/edk2-edkrepo/pull/119

**Comment by ashedesimone** [comment]
Merged to main branch.
