### ISSUE TITLE
Edkrepo fails to install with Python3.11

### ISSUE THREAD

**Issue by nnikolov-intel** [tianocore/edk2-edkrepo#120]
![edkrepoSetup-with-Python-3 11](https://user-images.githubusercontent.com/93952168/214707337-770ed881-b2b3-4e4b-b77a-09d7e865f403.png)

Accidentally, I installed Python 3.11. 
Windows set the Python launcher to 3.11.

I tried installing edkrepo, and it failed.

I am only opening this issue as FYI. There may be some dependencies that will break the edkrepo installation in the future.

**Comment by ndhaller** [comment]
Python 3.11 deprecated inspect.getargspec()
https://docs.python.org/3.11/library/inspect.html

Python 3.8 and Python 3.9 and Python 3.10 and Python 3.11 support getfullargspec() as "usually a drop-in replacement" for getargspec().
https://docs.python.org/3.8/library/inspect.html
https://docs.python.org/3.9/library/inspect.html
https://docs.python.org/3.10/library/inspect.html
https://docs.python.org/3.11/library/inspect.html

Replacing both instances of getargspec() with getfullargspec(), and the EdkRepoSetup-3.1.0.0.exe installer can be built and run on Windows 11 with python-3.11.1-amd64.exe

With those two line changes, not seeing any other initial problems with using Python 3.11

Test python 3.11.1: 
Install python-3.11.1-amd64.exe with default installation settings
py -3 -m pip install wheel
cd build-scripts
build_windows_installer.bat
cd ../dist
Install edkrepo 3.1.0 through EdkRepoSetup-3.1.0.0.exe
Installation Successful
run some test commands:
edkrepo manifest
edkrepo clone
edkrepo status
edkrepo combo
edkrepo checkout
edkrepo sync -u
python 3.11.1 basic functional tests pass

**Comment by ndhaller** [comment]
Confirmed, the Windows installer does not support Python 3.7.9.  It is a hard installer failure, not optional:

Test python 3.7.9: fail
Install python-3.7.9-amd64.exe with default installation settings
Install edkrepo 3.1.0 through EdkRepoSetup-3.1.0.0.exe
Installation Failed:
"""
Found Python 3.7.9
Error: Python version 3.8.8 or later is required to run EdkRepo. Please install it before continuing.
Installation Failed.
"""
