### ISSUE TITLE
edkrepo is not functioning with Windows install from source steps 

### ISSUE THREAD

**Issue by ndhaller** [tianocore/edk2-edkrepo#122]
On Windows 11 with Python 3.7.9 installed, followed the build steps in the readme.md

    py -3 -m pip install wheel
    cd build-scripts
    build_windows_installer.bat
    
    cd ..
    py -3 setup.py install

edkrepo commands fail with the error:  
The system cannot find the file C:\windows\edkrepo.exe.  
  
Running the generated "dist/EdkRepoSetup-3.1.0.0.exe" file fails with:  
"""
Found Python 3.7.9
Error: Python version 3.8.8 or later is required to run EdkRepo. Please install it before continuing.
Installation Failed.
"""
  
If edkrepo is going to say it has Python 3.5 and later support on Windows, need one of the install methods such as the install from source steps to work for Python 3.7.9.

**Comment by ashedesimone** [comment]
The ReadMe.md has been updated to list Python 3.8.8 or later as a requirement.
