### ISSUE TITLE
edkrepo clean -x request

### ISSUE THREAD

**Issue by ndhaller** [tianocore/edk2-edkrepo#125]
Can 'edkrepo clean' add support for [-x] as an argument similar to 'git clean [-x]' ?

e.g. 'edkrepo clean -fdx'

**Comment by ashedesimone** [comment]
@ndhaller  I assume you would like support for both -x and -X ?

**Comment by ndhaller** [comment]
I don't personally use -X for anything.  The git clean documentation currently has a note that -x can be used in conjunction with other commands "to create a pristine working directory to test a clean build." That would be my main use case for the new option.

https://git-scm.com/docs/git-clean
