### ISSUE TITLE
edkrepo checkout with SparseData combination can have wrong sparse files checked out.

### ISSUE THREAD

**Issue by ndhaller** [tianocore/edk2-edkrepo#131]
If you have two combo ("combo_A" and "combo_B"), both with sparseCheckout="true" on a remote repo ("repo"), but there is a <SparseData remote="repo" combination="combo_A"> section defined for "combo_A", and a global <SparseData> section used by all combo, the following two cases can happen:

While on "combo_A", running "edkrepo checkout combo_B" will not run the "Resetting sparse checkout state..." step and "Performing sparse checkout..." step.
While on "combo_B", running "edkrepo  checkout combo_A" will not run the "Resetting sparse checkout state..." step and "Performing sparse checkout..." step.  
-workaround: calling "edkrepo sync" after the 'checkout' command will reset to correct sparse checkout settings. 

While on "combo_A", running "edkrepo checkout combo_A" will always cause the "Resetting sparse checkout state..." step and "Performing sparse checkout..." step to be run.
-workaround: none.  this just makes the edkrepo checkout command take longer.

test environment: edkrepo 3.1.0, Python 3.8.10, git 2.39.1.windows.1, Windows 11.

**Comment by nate-desimone** [comment]
Good catch @ndhaller! And thank you so much for fixing the bug!
