### ISSUE TITLE
clone with both --treeless and --blobless encounter git error

### ISSUE THREAD

**Issue by ndhaller** [tianocore/edk2-edkrepo#247]
Is edkrepo clone ```--treeless``` and ```--blobless``` supported at the same time, or should one override the other if both are supplied?

```edkrepo clone Intel-MinPlatform Intel-MinPlatform --treeless --blobless```

```
Cloning edk2 Repository from: https://github.com/tianocore/edk2.git
Cloning into 'C:\git2\temp\Intel-MinPlatform-tree-blob\edk2'...
fatal: remote error: filter 'combine' not supported
Error: C:\git2\temp\Intel-MinPlatform-tree-blob\edk2
```

Test system: Windows 11, git version 2.43.0.windows.1 
I see combine filters is documented for my git version, but the error persists with manual git commands.
https://git-scm.com/docs/git-rev-list/2.43.0
```
Multiple --filter= flags can be specified to combine filters. Only objects which are accepted by every filter are included.
```

```
C:\git\temp>git clone https://github.com/tianocore/edk2-platforms edk2-platforms --filter=blob:none --filter=tree:0
Cloning into 'edk2-platforms'...
fatal: remote error: filter 'combine' not supported

C:\git\temp>git clone https://github.com/tianocore/edk2-platforms edk2-platforms --filter=combine:blob:none+tree:0
Cloning into 'edk2-platforms'...
fatal: remote error: filter 'combine' not supported
```

**Comment by ashedesimone** [comment]
My preference would be to error out and let the user make the choice ... these should be set up to be mutually exclusive args.
