### ISSUE TITLE
Error: The GitHub username was not found.

### ISSUE THREAD

**Issue by singhvaibhavdeep** [tianocore/edk2-edkrepo#72]
I am suddenly seeing access issues while raising code review.

$ edkrepo send-review --title xml_dram_cmos
Creating review for branch "xml_cmo" in local repository "D:\Vaibhav\srvrgen3\Intel\.git" pushing to branch "main" on remote url "https://github.com/intel-restricted/firmware.boot.uefi.iafw.intel"
Error: The GitHub username for: 96463321+singhvaibhavdeep@users.noreply.github.com was not found.

Can anyone help please?

**Comment by ashedesimone** [comment]
> I am suddenly seeing access issues while raising code review.
> 
> $ edkrepo send-review --title xml_dram_cmos Creating review for branch "xml_cmo" in local repository "D:\Vaibhav\srvrgen3\Intel.git" pushing to branch "main" on remote url "https://github.com/intel-restricted/firmware.boot.uefi.iafw.intel" Error: The GitHub username for: [96463321+singhvaibhavdeep@users.noreply.github.com](mailto:96463321+singhvaibhavdeep@users.noreply.github.com) was not found.
> 
> Can anyone help please?

This issue is not related to any open source content I am closing it.
